import React from "react";
import { Metadata } from "next";
import Image from "next/image";
import Card from "@/components/ui/Card";
import Badge from "@/components/ui/Badge";
import Button from "@/components/ui/Button";
import AnswerBlock from "@/components/seo/AnswerBlock";
import VideoBackground from "@/components/ui/VideoBackground";
import StockImage from "@/components/ui/StockImage";
import VishAiHero from "@/components/ui/VishAiHero";
import { Brain, MessageSquare, Terminal, ArrowRight } from "lucide-react";

export const metadata: Metadata = {
  title: "Vish AI | Manufacturing Intelligence Layer",
  description: "Vish AI is the manufacturing intelligence layer that uses Df-OS factory memory to answer questions, explain deviations, detect patterns, prioritize actions, and support faster decisions.",
  alternates: {
    canonical: "https://df-os.com/platform/vish-ai",
  },
};

export default function VishAiProductPage() {
  const sampleQueries = [
    {
      q: "Which batches are at risk today and why?",
      a: "Batch FMCG-206 is flagged. Line 4 changeover recorded a process deviation (nozzle pressure exceeded 4.2 bar). Action: Calibrate valve settings."
    },
    {
      q: "Why did yield drop after the last changeover?",
      a: "Changeover PM logs show technician did not complete seal alignment checks. Motor frequency fluctuated by 12% immediately after start."
    },
    {
      q: "What were the top recurring downtime reasons this week?",
      a: "1. Packaging Line 2 feeder jams (12 instances, 45m total). 2. Labeler sensor calibration faults (8 instances, 32m total)."
    }
  ];

  return (
    <div className="w-full">
      {/* Hero Section */}
      <VishAiHero />

      {/* Section 1: Positioning */}
      <section className="py-16 md:py-24 bg-[#09090d] border-b border-brand-border/40">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
            
            {/* Left Content */}
            <div className="lg:col-span-7 flex flex-col gap-6">
              <Badge variant="green">Intelligence Layer</Badge>
              <h2 className="text-3xl md:text-4xl lg:text-5xl font-black tracking-tight leading-tight text-shimmer">
                Built for the Next Era of Connected Manufacturing
              </h2>
              <p className="text-slate-300 text-sm md:text-base leading-relaxed">
                Traditional dashboards show you what happened, but they leave the burden of explanation, correlation, and action on your teams. 
              </p>
              <p className="text-slate-400 text-xs md:text-sm leading-relaxed">
                Vish AI changes this. By reasoning over the continuous timeline generated by Df-OS (&ldquo;factory memory&rdquo;), Vish AI explains deviations, flags risk patterns, compiles reviews, and provides actionable recommendations. It turns raw factory data into clear, operational decisions.
              </p>
            </div>

            {/* Right Graphic Core */}
            <div className="lg:col-span-5 border border-brand-border bg-brand-card/30 p-6 rounded-xl relative overflow-hidden flex flex-col items-center justify-center min-h-[300px]">
              <div className="absolute inset-0 blueprint-grid-fine opacity-30" />
              <div className="w-20 h-20 bg-brand-green/10 border border-brand-green/20 rounded-full flex items-center justify-center shadow-lg shadow-brand-green/5 animate-pulse relative z-10 mb-4">
                <Brain className="w-10 h-10 text-brand-green" />
              </div>
              <span className="text-xs font-mono text-brand-green font-bold tracking-wider relative z-10 uppercase mb-2">
                Explainable Decision Engine
              </span>
              <p className="text-[10px] text-slate-500 text-center max-w-xs relative z-10 leading-relaxed mb-4">
                Vish AI analyzes human execution variables alongside live machine parameters to recommend actions.
              </p>
              <div className="relative w-full h-28 rounded-lg overflow-hidden border border-brand-border/50">
                <Image
                  src="/images/stock/digital-wireframe.jpg"
                  alt="Digital brain network abstract wireframe"
                  fill
                  className="object-cover opacity-40 hover:opacity-60 transition-opacity"
                  sizes="(max-width: 768px) 100vw, 33vw"
                />
              </div>
            </div>

          </div>
        </div>
      </section>

      {/* Section 2: Conversational AI */}
      <section id="capabilities" className="py-16 md:py-24 bg-brand-bg border-b border-brand-border/40">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
            
            {/* Left Sample Queries */}
            <div className="lg:col-span-5 flex flex-col gap-4">
              <div className="flex items-center gap-2 mb-2">
                <MessageSquare className="w-5 h-5 text-brand-green" />
                <span className="text-xs font-mono text-brand-green uppercase tracking-wider font-semibold">
                  Interactive Intelligence Chat
                </span>
              </div>
              <div className="flex flex-col gap-4">
                {sampleQueries.map((item, idx) => (
                  <div key={idx} className="flex flex-col gap-2">
                    {/* User Question */}
                    <div className="self-start mr-12 bg-[#1b1b26]/75 border border-brand-border/80 px-4 py-2.5 rounded-2xl rounded-tl-none text-[11px] text-slate-200 font-sans shadow-sm max-w-[90%]">
                      <span className="text-brand-green font-bold mr-1">User:</span> &ldquo;{item.q}&rdquo;
                    </div>
                    {/* AI Answer */}
                    <div className="self-end ml-12 bg-brand-green/5 border border-brand-green/20 px-4 py-2.5 rounded-2xl rounded-tr-none text-[11px] text-slate-300 max-w-[90%] shadow-[0_4px_20px_rgba(16,185,129,0.02)]">
                      <div className="flex items-center gap-1.5 mb-1.5">
                        <span className="w-1.5 h-1.5 rounded-full bg-brand-green signal-dot" />
                        <span className="text-[9px] font-mono text-brand-green uppercase tracking-wider font-bold">Vish AI</span>
                      </div>
                      <p className="leading-relaxed font-sans">{item.a}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Right Content */}
            <div className="lg:col-span-7 flex flex-col gap-6 lg:pl-6">
              <Badge variant="green">Conversational AI</Badge>
              <h2 className="text-3xl md:text-4xl lg:text-5xl font-black tracking-tight leading-tight text-shimmer">
                Ask Your Factory, Understand Deviations
              </h2>
              <p className="text-slate-300 text-sm md:text-base leading-relaxed">
                Vish Conversational AI allows operators, plant heads, and quality managers to query factory status using natural language. No more building custom databases or searching through Excel sheets.
              </p>
              <p className="text-slate-400 text-xs md:text-sm leading-relaxed">
                Whether you need to check batch release statuses, compare PM response times, or count shift deviations, simply ask the system. Vish AI compiles the data instantly and provides answers in operational context.
              </p>
            </div>

          </div>
        </div>
      </section>

      {/* Section 3: Agentic AI */}
      <section className="py-16 md:py-24 bg-[#09090d] border-b border-brand-border/40">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
            
            {/* Left Content */}
            <div className="lg:col-span-7 flex flex-col gap-6">
              <Badge variant="green">Agentic AI Assistants</Badge>
              <h2 className="text-3xl md:text-4xl lg:text-5xl font-black tracking-tight leading-tight text-shimmer">
                Deploy Digital Subject Matter Experts
              </h2>
              <p className="text-slate-300 text-sm md:text-base leading-relaxed">
                Vish AI enables you to deploy specialized AI agents configured as digital Subject Matter Experts (SMEs) across core manufacturing disciplines.
              </p>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mt-2">
                <Card variant="green" className="p-4 flex flex-col gap-2">
                  <h4 className="text-xs font-bold text-white uppercase font-mono tracking-wider flex items-center gap-1.5">
                    <span className="w-1.5 h-1.5 rounded-full bg-brand-green" />
                    Quality Agent
                  </h4>
                  <p className="text-[11px] text-slate-400 leading-relaxed">
                    Monitors in-process checks, matches raw parameters against SOPs, alerts on deviation risks, and drafted RCA templates.
                  </p>
                </Card>
                <Card variant="green" className="p-4 flex flex-col gap-2">
                  <h4 className="text-xs font-bold text-white uppercase font-mono tracking-wider flex items-center gap-1.5">
                    <span className="w-1.5 h-1.5 rounded-full bg-brand-green" />
                    Maintenance Agent
                  </h4>
                  <p className="text-[11px] text-slate-400 leading-relaxed">
                    Tracks asset indicators, alarms, and PM delays, predicting early failures and recommending spare parts checklists.
                  </p>
                </Card>
                <Card variant="green" className="p-4 flex flex-col gap-2">
                  <h4 className="text-xs font-bold text-white uppercase font-mono tracking-wider flex items-center gap-1.5">
                    <span className="w-1.5 h-1.5 rounded-full bg-brand-green" />
                    Production Agent
                  </h4>
                  <p className="text-[11px] text-slate-400 leading-relaxed">
                    Monitors plan vs actual compliance, downtime events, and SKU changeover variables to improve overall OEE.
                  </p>
                </Card>
                <Card variant="green" className="p-4 flex flex-col gap-2">
                  <h4 className="text-xs font-bold text-white uppercase font-mono tracking-wider flex items-center gap-1.5">
                    <span className="w-1.5 h-1.5 rounded-full bg-brand-green" />
                    Utility & ESG Agent
                  </h4>
                  <p className="text-[11px] text-slate-400 leading-relaxed">
                    Flags utility leakages, watches peak consumption limits, and compiles carbon emissions metrics.
                  </p>
                </Card>
              </div>
            </div>

            {/* Right: AnswerBlock / AEO Focus */}
            <div className="lg:col-span-5 flex flex-col gap-6">
              <AnswerBlock
                question="How do Vish AI Agents operate on the shop floor?"
                answer="Vish AI agents do not act autonomously in a vacuum. They run in a 'human-in-the-loop' configuration. The agents continuously scan Df-OS records for anomalies, compile findings, recommend corrective tasks, and notify supervisors, leaving the final approval and execution authority in human hands."
              />
              <StockImage
                src="/images/stock/engineer-tablet.jpg"
                alt="Technician reviewing maintenance checklists on industrial tablet"
                overlay="gradient"
              />
            </div>

          </div>
        </div>
      </section>

      {/* Section 4: Explainable AI & Factory Memory */}
      <section className="py-16 md:py-24 bg-brand-bg border-b border-brand-border/40">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
            
            {/* Left Graphic */}
            <div className="lg:col-span-5 border border-brand-border bg-brand-card/30 p-6 rounded-xl relative overflow-hidden min-h-[300px] flex flex-col justify-between hover:border-brand-green/35 transition-colors duration-500">
              <div className="absolute inset-0 blueprint-grid-fine opacity-20" />
              <div className="flex items-center gap-2 relative">
                <Terminal className="w-5 h-5 text-brand-green" />
                <span className="text-xs font-mono text-brand-green uppercase tracking-wider font-semibold">
                  Factory Memory Map
                </span>
              </div>
              <div className="flex flex-col gap-3 relative border-l border-brand-green/30 pl-4 py-2">
                <div className="text-[10px] font-mono text-slate-400 flex items-center gap-2">
                  <span className="w-1.5 h-1.5 rounded-full bg-slate-500" />
                  <span>[STEP 1] Machine parameters mapped via X-Konnect</span>
                </div>
                <div className="text-[10px] font-mono text-slate-400 flex items-center gap-2">
                  <span className="w-1.5 h-1.5 rounded-full bg-slate-500" />
                  <span>[STEP 2] Checklists & Handover structured via Df-OS</span>
                </div>
                <div className="text-[10px] font-mono text-slate-200 font-semibold flex items-center gap-2">
                  <span className="w-1.5 h-1.5 rounded-full bg-brand-green signal-dot" />
                  <span className="text-brand-green">[STEP 3] Vish AI explains anomalies in context</span>
                </div>
              </div>
              <span className="text-[9px] font-mono text-slate-500 relative">
                Traceable AI reasoning paths
              </span>
            </div>

            {/* Right Content */}
            <div className="lg:col-span-7 flex flex-col gap-6 lg:pl-6">
              <Badge variant="green">Traceable Logic</Badge>
              <h2 className="text-3xl md:text-4xl lg:text-5xl font-black tracking-tight leading-tight text-shimmer">
                Explainable Decisions, High Trust
              </h2>
              <p className="text-slate-300 text-sm md:text-base leading-relaxed">
                Industrial environments require high-trust reasoning. General-purpose AI models often suffer from hallucinations and lack specific factory context.
              </p>
              <p className="text-slate-400 text-xs md:text-sm leading-relaxed">
                Vish AI uses **traceable, explainable logic**. Every recommendation, anomaly flag, or priority score is linked back to a specific record in Df-OS&apos;s factory memory (such as a checklist input, a PLC status stream, or a historical resolution). This enables operators and plant leaders to audit the AI&apos;s reasoning path before executing actions.
              </p>
            </div>

          </div>
        </div>
      </section>

      {/* Section 5: CTA */}
      <section className="relative border-b border-brand-border/40 overflow-hidden">
        <VideoBackground
          src="/videos/particle-ring.mp4"
          className="py-24"
          overlayClassName="bg-brand-bg/10 bg-[radial-gradient(circle_at_center,rgba(7,7,10,0.05)_0%,rgba(7,7,10,0.7)_100%)]"
        >
          <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 relative text-center flex flex-col gap-6">
            <Badge variant="green" className="mx-auto">Book a Demo</Badge>
            <h2 className="text-3xl md:text-5xl lg:text-6xl font-black tracking-tight leading-tight text-shimmer drop-shadow-[0_2px_8px_rgba(0,0,0,0.8)]">
              Ready to Deploy Vish AI in Your Factory?
            </h2>
            <p className="text-slate-300 text-base leading-relaxed max-w-xl mx-auto drop-shadow-[0_2px_4px_rgba(0,0,0,0.8)]">
              See how Vish AI turns structured factory memory into faster decisions. Request an interactive demo showing conversational and agentic assistants.
            </p>
            <div className="mt-2 flex justify-center">
              <Button href="/contact" variant="primary" className="group">
                Book an AI Demo
                <ArrowRight className="w-4 h-4 ml-1.5 transition-transform group-hover:translate-x-1" />
              </Button>
            </div>
          </div>
        </VideoBackground>
      </section>
    </div>
  );
}
